rails/config/routes.rb
WWW140kit::Application.routes.draw do

  resources :auth_users

  resources :analytical_offerings, path: '/analytics', only: [:index, :edit, :new, :create] do
    member do
      put 'details' => :update, as: :update
      get 'details' => :show, as: ''
      get ':curation_id/add' => :add, as: :add
      post ':curation_id/validate' => :validate, as: :validate
      get ':curation_id/verify' => :verify, as: :verify
    end
  end

  scope '/analytics/:id' do
    get '' => 'analysis_metadata#show', as: :analysis_metadata
    get ':graph_id/graph' => 'analysis_metadata#graph', as: :analysis_metadata_graph
    delete '' => 'analysis_metadata#destroy'
  end

  resources :instances, only: [] do
    member do
      get 'kill' => :kill_instance
      get ':id' => :show_instance, as: ''
    end
    get '' => :index_instance, as: '', on: :collection
  end

  resources :instances, as: :machines, path: '/machines', only: [] do
    get '' => :index_machine, as: '', on: :collection
    member do
      get 'edit' => :edit
      get 'kill' => :kill_machine
      get '' => :show_machine, as: ''
      post 'update' => :update
    end
  end

  get '/datasets/new/location' => 'curations#new_location', as: :new_location_dataset
  get '/datasets/new/term' => 'curations#new_term', as: :new_term_dataset
  get '/datasets/new/user' => 'curations#new_user', as: :new_user_dataset
  get '/datasets/validate/users' => 'curations#validate_users', as: :validate_user_dataset
  get '/datasets/:id/alter/:stream_type' => 'curations#new', as: :alter_dataset
  get '/tags/drop_relation' => 'tags#drop_relation', as: :drop_tag_relation
  resources :curations, only: [:index, :create, :new, :show, :validate, :analyze, :alter, :import, :verify, :destroy], path: '/datasets', as: :datasets do
    member do
      get 'verify'
      get 'analyze'
      get 'import'
      get 'archive'
    end
    get 'search', on: :collection
  end
  post '/datasets/validate' => 'curations#validate', as: :dataset_validate
  get '/:user_name/datasets' => 'curations#researcher', as: :researcher_datasets
  get '/analysis/:curation_id/:analysis_metadata_id' => 'analysis_metadata#results', as: :curation_analysis

  get '/admin/panel' => 'admin#panel', as: :admin_panel

  resources :researchers, only: [:index]
  scope '/researchers/:user_name' do
    get '' => 'researchers#show', as: :researcher
    get 'edit' => 'researchers#edit', as: :edit_researcher
    get 'new' => 'researchers#new', as: :new_researcher
    get 'upgrade' => 'researchers#upgrade', as: :upgrade_researcher
    get 'request_upgrade' => 'researchers#request_upgrade', as: :request_upgrade_researcher
    put '' => 'researchers#update'
    delete '' => 'researchers#destroy'
  end
  get '/datasets/:curation_id/tweets/' => 'tweets#index', as: :tweets
  get '/datasets/:curation_id/users/' => 'users#index', as: :users

  get 'dashboard' => 'researchers#dashboard', as: :dashboard

  resources :posts, except: [:show]
  get '/posts/search' => 'posts#index', as: :search_posts

  get '/posts/:id/:slug' => 'posts#show', as: :post
  get '/about' => 'posts#about', as: :about

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root to: 'home#index'
  resources :analytical_offering_variable_descriptors, path: '/variables'
  get '/dependencies/:id/new' => 'analytical_offering_requirements#new', as: :new_dependency
  resources :analytical_offering_requirements, path: '/dependencies'
  get '/variables/:id/new' => 'analytical_offering_variable_descriptors#new', as: :new_variable
  resources :tags
  resources :settings

end

rails/app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WWW140kit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<span class="notice"><%= flash[:notice] %></span>
<span class="error"><%= flash[:error] %></span>
<%= yield %>

</body>
</html>

rails/app/views/layouts/_nav.html.slim
// this is a template for a possible navbar we'd put in some views

.navbar
  .navbar-inner
    .container style='width: auto;'
      a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.brand href="#" Project name
      .nav-collapse
        ul.nav
          li.active
            a href="#" Home
          li
            a href='#' Link
          li
            a href='#' Link
          li
            a href='#' Link
          li.dropdown
            a.dropdown-toggle data-toggle='dropdown'
              | Dropdown 
              b.caret
            ul.dropdown-menu
              li
                a href='#' Action
              li
                a href='#' Another action
              li
                a href='#' Yet another action
              li.divider
              li.nav-header Nav Header
              li
                a href='#' Separated link
        ul.nav.pull-right
          li
            a href='#' Link
          li.divider-vertical
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              | Dropdown 
              b.caret
            ul.dropdown-menu
              li
                a href='#' Action
              li
                a href='#' Another action
              li
                a href='#' Yet another action
              li.divider
              li
                a href='#' Separated link

rails/app/views/layouts/application.html.slim
doctype 5
html
  head
    title
      | 140kit
      = ": #{@page_title}" if @page_title
    /[if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
    // = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "http://code.highcharts.com/highcharts.js", "http://code.highcharts.com/modules/exporting.js", "https://www.google.com/jsapi", "application"
    // = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application"
    = stylesheet_link_tag "application"
    /* link rel="stylesheet" href="/css/bootstrap-responsive.min.css"*/
    link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon"
    = csrf_meta_tags
    // script type='text/javascript' google.load('visualization', '1', {packages:['table', 'annotatedtimeline']});
    /* script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"*/
    /* script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"*/
    /* script src="/js/bootstrap.min.js" type="text/javascript"*/
    //, "https://www.google.com/jsapi", "application"
    = javascript_include_tag 'application'
    = javascript_include_tag "http://code.highcharts.com/highcharts.js", "http://code.highcharts.com/modules/exporting.js"
    = javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"
  body

    .navbar#main-nav
      // .navbar-fixed-top
      .navbar-inner
        .container
          .stripe
          a.brand href=root_path 140kit
          .nav-collapse
            ul.nav#global-nav
              li class=('active' if current_route?('researchers#index'))
                = link_to 'Researchers', researchers_path
              li class=('active' if current_route?('curations#index'))
                = link_to 'Datasets', datasets_path
              li class=('active' if current_route?('analytical_offerings#index'))
                = link_to 'Analytics', analytical_offerings_path
              li class=('active' if current_route?('posts#index'))
                = link_to 'News', posts_path
            ul.nav.pull-right#user-nav
              - if current_user
                li class=('active' if current_route?('researchers#dashboard'))
                  = link_to "Dashboard", dashboard_path
                li class=('active' if (current_route?('researchers#show') && current_user.user_name == params[:user_name]))
                  = link_to "Me", researcher_path(current_user)
                - if current_user && current_user.admin?
                  li class=('active' if current_route?('admin#panel'))
                    = link_to 'Admin', admin_panel_path
                li
                  = link_to 'Sign out', signout_path
              - else
                li
                  a href="/auth/twitter"
                    // FIXME: do not hotlink twitterbird
                    span style='background:url(https://si0.twimg.com/images/dev/cms/intents/bird/bird_blue/bird_16_blue.png) 0 50% transparent no-repeat; padding-left:22px;' Sign in with Twitter

    .container#main

      - flash.each do |k,v|
        div class="alert alert-#{k} align-center"
          a.close data-dismiss="alert" ×
          strong = v
      == yield
      
      hr

    .container
      footer
        a href="/posts/5/policy" style="color:#888" cc-by-nc-sa 140kit, 2012


    script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"

    javascript:
      $(function() {
        $('.dropdown-toggle').dropdown();
        $('.alert').alert();
        $('form').validate();
        $('#time-slider').slider({
            min: 60,
            max: 604800,
            slide: function(event, ui) {
                $('#time_output').html(exact_time(reasonableIncrement(ui.value)));
                $('#end_time').val(ui.value);
              }
        });
        $('#main').on('click', '#back-to-new-curation', function() { $('#curation-form').slideUp(); $('#term-or-location-or-user').slideDown(); });
        $('#main').on('click', '#overview-header', function() { $('#overview').slideToggle();$('#overview-plus').slideToggle();});
        $('#main').on('click', '#analytics-header', function() { $('#analytics').slideToggle();$('#analytics-plus').slideToggle();});
        $('#main').on('click', '#tags-header', function() { $('#tags').slideToggle();$('#tags-plus').slideToggle();});
        $('#main').on('click', '#data-header', function() { $('#data').slideToggle();$('#data-plus').slideToggle();});
        $('#main').on('click', '#discussion-header', function() { $('#discussion').slideToggle();$('#discussion-plus').slideToggle();});
        // $('.comma-separated-input').tagsInput({ height:'20px', defaultText: 'add a term', placeholderColor: '#999' });
        $('#main').on('click', '#review-curation-params', function() {
          if ( !$('#new-curation-form').valid() ) return false;
          var terms = $('#terms').val()
            , users = $('#users').val()
            , latlon = $('#latlon').val()
            , name = $('#name').val()
            , humanTime = $('#time_output').text()
            , endTime = $('#end_time').val()
            , streamType = $('#stream_type').val()
            , modal = '';
          modal += '<div class="modal hide" id="review-curation-modal">';
          modal += '<div class="modal-header">';
          modal += '<a class="close" data-dismiss="modal">×</a>';
          modal += '<h3>Review dataset</h3>';
          modal += '</div>';
          modal += '<div class="modal-body">';
          modal += '<ul>';
          if (streamType == 'terms') {
            modal += '<li>Name: ' + (name || terms)  + '</li>';
            modal += '<li>Tracking tweets matching terms: ' + terms + '</li>';
          } else if (streamType == 'location') {
            modal += '<li>Name: ' + (name || latlon) + '</li>';
            modal += '<li>Tracking geotagged tweets matching coordinates in: ' + latlon + '</li>';
          } else if (streamType == 'users') {
            modal += '<li>Name: ' + (name) + '</li>';
            modal += '<li>Tracking tweets from users: ' + users + '</li>';
          }
          modal += '<li>Collect for: ' + humanTime + '</li>';
          modal += '</ul>';
          modal += '</div>';
          modal += '<div class="modal-footer">';
          modal += '<a id="submit-curation-button" class="btn btn-success btn-large">Start collecting!</a>';
          modal += '<a data-dismiss="modal" class="btn btn-large">Make changes</a>';
          modal += '</div>';
          modal += '</div>';

          $('#review-curation-modal').remove();
          $('body').append(modal);
          $('#submit-curation-button').click(function() { $('#new-curation-form').submit(); });
          $('#review-curation-modal').modal();
        });

      });
      function validate_users(value){
        //hello
        $('a#review-curation-params').text("Waiting on Validation...");
        $('a#review-curation-params').attr("id", "review-curation-params-hold");
        $.get('/datasets/validate/users?screen_names='+value, function(data) {
          $('.result').html(data);
          $('input#users').val(data);
          $('a#review-curation-params-hold').attr("id", "review-curation-params");
          $('a#review-curation-params').text("Submit");
        });
      }
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-16471158-1']);
      _gaq.push(['_setDomainName', '140kit.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();