rails/config/routes.rb
WWW140kit::Application.routes.draw do

  resources :auth_users

  resources :analytical_offerings, path: '/analytics', only: [:index, :edit, :new, :create] do
    member do
      put 'details' => :update, as: :update
      get 'details' => :show, as: ''
      get ':curation_id/add' => :add, as: :add
      post ':curation_id/validate' => :validate, as: :validate
      get ':curation_id/verify' => :verify, as: :verify
    end
  end

  scope '/analytics/:id' do
    get '' => 'analysis_metadata#show', as: :analysis_metadata
    get ':graph_id/graph' => 'analysis_metadata#graph', as: :analysis_metadata_graph
    delete '' => 'analysis_metadata#destroy'
  end

  resources :instances, only: [] do
    member do
      get 'kill' => :kill_instance
      get ':id' => :show_instance, as: ''
    end
    get '' => :index_instance, as: '', on: :collection
  end

  resources :instances, as: :machines, path: '/machines', only: [] do
    get '' => :index_machine, as: '', on: :collection
    member do
      get 'edit' => :edit
      get 'kill' => :kill_machine
      get '' => :show_machine, as: ''
      post 'update' => :update
    end
  end

  get '/datasets/new/location' => 'curations#new_location', as: :new_location_dataset
  get '/datasets/new/term' => 'curations#new_term', as: :new_term_dataset
  get '/datasets/new/user' => 'curations#new_user', as: :new_user_dataset
  get '/datasets/validate/users' => 'curations#validate_users', as: :validate_user_dataset
  get '/datasets/:id/alter/:stream_type' => 'curations#new', as: :alter_dataset
  get '/tags/drop_relation' => 'tags#drop_relation', as: :drop_tag_relation
  resources :curations, only: [:index, :create, :new, :show, :validate, :analyze, :alter, :import, :verify, :destroy], path: '/datasets', as: :datasets do
    member do
      get 'verify'
      get 'analyze'
      get 'import'
      get 'archive'
    end
    get 'search', on: :collection
  end
  post '/datasets/validate' => 'curations#validate', as: :dataset_validate
  get '/:user_name/datasets' => 'curations#researcher', as: :researcher_datasets
  get '/analysis/:curation_id/:analysis_metadata_id' => 'analysis_metadata#results', as: :curation_analysis

  get '/admin/panel' => 'admin#panel', as: :admin_panel

  resources :researchers, only: [:index]
  scope '/researchers/:user_name' do
    get '' => 'researchers#show', as: :researcher
    get 'edit' => 'researchers#edit', as: :edit_researcher
    get 'new' => 'researchers#new', as: :new_researcher
    get 'upgrade' => 'researchers#upgrade', as: :upgrade_researcher
    get 'request_upgrade' => 'researchers#request_upgrade', as: :request_upgrade_researcher
    put '' => 'researchers#update'
    delete '' => 'researchers#destroy'
  end
  get '/datasets/:curation_id/tweets/' => 'tweets#index', as: :tweets
  get '/datasets/:curation_id/users/' => 'users#index', as: :users

  get 'dashboard' => 'researchers#dashboard', as: :dashboard

  resources :posts, except: [:show]
  get '/posts/search' => 'posts#index', as: :search_posts

  get '/posts/:id/:slug' => 'posts#show', as: :post
  get '/about' => 'posts#about', as: :about

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root to: 'home#index'
  resources :analytical_offering_variable_descriptors, path: '/variables'
  get '/dependencies/:id/new' => 'analytical_offering_requirements#new', as: :new_dependency
  resources :analytical_offering_requirements, path: '/dependencies'
  get '/variables/:id/new' => 'analytical_offering_variable_descriptors#new', as: :new_variable
  resources :tags
  resources :settings

end

rails/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :researcher
  has_and_belongs_to_many :tags, :join_table => "post_tags"

  def self.latest_featured
    Post.where(:status => "featured").limit(1).order("created_at ASC").first
  end
  
  def teaser(length=250)
    words = self.text.gsub(/<.*>/, "")[0..length].split(" ")
    words[0..words.length-2].join(" ")+"..."
  end
end

rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :login_required, except: [:index, :show]
  before_filter :admin_required, only: [:update, :create, :edit, :destroy, :panel]
  
  def index
    if params[:tag_id]
      @posts = Tag.find(params[:tag_id]).posts.where(:status => "regular").paginate(:page => params[:page], :per_page => 10, :order => "created_at desc")
    else
      @posts = Post.where(:status => "regular").paginate(:page => params[:page], :per_page => 10, :order => "created_at desc")
    end
    @page_title = "News"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find_by_id_and_slug(params[:id], params[:slug])
    @tags = @post.tags
    @page_title = "Posts: #{@post.title}"
  end
  
  def new
    @post = Post.new
    @page_title = "New Post"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @page_title = "Editing Posts: #{@post.title}"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to post_path(@post.id, @post.slug), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

rails/app/helpers/posts_helper.rb
module PostsHelper
end

rails/app/views/posts/_form.html.slim
= form_for(@post) do |f|
  fieldset
    .span4    
      label.control-label Title
      .controls
        = f.text_field :title, class: 'input-xlarge'
      label.control-label Function
      .controls
        = f.text_field :slug, class: 'input-xlarge'
      label.control-label Text
      .controls
        = f.text_area :text, class: 'input-xxlarge'
      label.control-label Status
      .controls
        = f.select(:status, [['Regular', 'regular'],['Featured', 'featured'],['Hidden', 'hidden']], class: 'input-xlarge')
      = f.hidden_field :researcher_id, :value => current_user.id
    .span12
      .form-actions
        = submit_tag 'Submit', class: 'btn btn-primary'

rails/app/views/posts/edit.html.slim
== render partial: 'form'

rails/app/views/posts/index.html.slim
h1 News
hr 
- if @posts.empty?
  p No Posts Found.
- else
  - for post in @posts
    h2 = link_to post.title, post_path(post.id, post.slug)
    p = post.created_at.strftime('%B %d, %Y at %l:%M:%S %P')
    p = post.teaser
  = will_paginate(@posts)

- if current_user && current_user.admin?
  = link_to "Add Post", new_post_path

rails/app/views/posts/new.html.slim
== render partial: 'form'

rails/app/views/posts/show.html.slim
h1 = @post.title
p.byline 
  a href=researcher_path(@post.researcher.user_name) #{@post.researcher.user_name}
  = " at #{@post.created_at}"
= RedCloth.new(@post.text).to_html.html_safe

- if current_user && current_user.admin?
  = link_to "Edit", edit_post_path(@post)

- if !@tags.empty?
  h4 Tags:
  == render partial: '/tags/table', locals: {tags: @tags, classname: "Post", with_id: @post.id}
  hr
- if current_user && current_user.admin?
  == render partial: '/tags/form', locals: {tag: Tag.new, classname: "Post", with_id: @post.id}

== render partial: '/partials/disqus'