rails/config/routes.rb
WWW140kit::Application.routes.draw do

  resources :auth_users

  resources :analytical_offerings, path: '/analytics', only: [:index, :edit, :new, :create] do
    member do
      put 'details' => :update, as: :update
      get 'details' => :show, as: ''
      get ':curation_id/add' => :add, as: :add
      post ':curation_id/validate' => :validate, as: :validate
      get ':curation_id/verify' => :verify, as: :verify
    end
  end

  scope '/analytics/:id' do
    get '' => 'analysis_metadata#show', as: :analysis_metadata
    get ':graph_id/graph' => 'analysis_metadata#graph', as: :analysis_metadata_graph
    delete '' => 'analysis_metadata#destroy'
  end

  resources :instances, only: [] do
    member do
      get 'kill' => :kill_instance
      get ':id' => :show_instance, as: ''
    end
    get '' => :index_instance, as: '', on: :collection
  end

  resources :instances, as: :machines, path: '/machines', only: [] do
    get '' => :index_machine, as: '', on: :collection
    member do
      get 'edit' => :edit
      get 'kill' => :kill_machine
      get '' => :show_machine, as: ''
      post 'update' => :update
    end
  end

  get '/datasets/new/location' => 'curations#new_location', as: :new_location_dataset
  get '/datasets/new/term' => 'curations#new_term', as: :new_term_dataset
  get '/datasets/new/user' => 'curations#new_user', as: :new_user_dataset
  get '/datasets/validate/users' => 'curations#validate_users', as: :validate_user_dataset
  get '/datasets/:id/alter/:stream_type' => 'curations#new', as: :alter_dataset
  get '/tags/drop_relation' => 'tags#drop_relation', as: :drop_tag_relation
  resources :curations, only: [:index, :create, :new, :show, :validate, :analyze, :alter, :import, :verify, :destroy], path: '/datasets', as: :datasets do
    member do
      get 'verify'
      get 'analyze'
      get 'import'
      get 'archive'
    end
    get 'search', on: :collection
  end
  post '/datasets/validate' => 'curations#validate', as: :dataset_validate
  get '/:user_name/datasets' => 'curations#researcher', as: :researcher_datasets
  get '/analysis/:curation_id/:analysis_metadata_id' => 'analysis_metadata#results', as: :curation_analysis

  get '/admin/panel' => 'admin#panel', as: :admin_panel

  resources :researchers, only: [:index]
  scope '/researchers/:user_name' do
    get '' => 'researchers#show', as: :researcher
    get 'edit' => 'researchers#edit', as: :edit_researcher
    get 'new' => 'researchers#new', as: :new_researcher
    get 'upgrade' => 'researchers#upgrade', as: :upgrade_researcher
    get 'request_upgrade' => 'researchers#request_upgrade', as: :request_upgrade_researcher
    put '' => 'researchers#update'
    delete '' => 'researchers#destroy'
  end
  get '/datasets/:curation_id/tweets/' => 'tweets#index', as: :tweets
  get '/datasets/:curation_id/users/' => 'users#index', as: :users

  get 'dashboard' => 'researchers#dashboard', as: :dashboard

  resources :posts, except: [:show]
  get '/posts/search' => 'posts#index', as: :search_posts

  get '/posts/:id/:slug' => 'posts#show', as: :post
  get '/about' => 'posts#about', as: :about

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root to: 'home#index'
  resources :analytical_offering_variable_descriptors, path: '/variables'
  get '/dependencies/:id/new' => 'analytical_offering_requirements#new', as: :new_dependency
  resources :analytical_offering_requirements, path: '/dependencies'
  get '/variables/:id/new' => 'analytical_offering_variable_descriptors#new', as: :new_variable
  resources :tags
  resources :settings

end

rails/app/models/researcher.rb
class Researcher < ActiveRecord::Base

  has_many :curations
  has_many :posts

  validates :name, :user_name, presence: true
  validates :uid, :oauth_token, :oauth_token_secret, presence: true, uniqueness: true,  on: :create
  validates :user_name, uniqueness: true
  validates :email, uniqueness: true, email: true, presence: true, on: :update
  # validates :website_url, :affiliation_url, format: { with: URI::regexp(%w(http https)), message: "Invalid URL! Try adding 'http://'" }

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.oauth_token = auth["credentials"]["token"]
      user.oauth_token_secret = auth["credentials"]["secret"]
      user.user_name = auth.extra.raw_info.screen_name
      user.name = auth.extra.raw_info.name
      user.location = auth.extra.raw_info.location
      user.website_url = auth.extra.raw_info.url
      user.info = auth.extra.raw_info.description
      user.affiliation_url = "http://140kit.com"
      user.role = Researcher.count == 0 ? "Admin" : "User"
      user.join_date = Time.now
      user.first_time = true
    end
  end

  def twitter_url
    "http://twitter.com/#{self.user_name}"
  end

  def twitter_pic(size)
    # :bigger, :normal, :mini, :original
    "https://api.twitter.com/1/users/profile_image?screen_name=#{self.user_name}&size=#{size.to_s}"
  end

  def to_param
    self.user_name
  end
  
  def human_join_date
    return self.join_date.strftime("%b %d, %Y")
  end
  
  def self.roles
    return Setting.find_by_name("roles").value
  end
  
  def admin?
    return Researcher.find(self.id).role == "Admin"
  end
  
  def curations_count
    return curations.count
  end
  
  def safe_website_url
    if self.website_url[0..6] != "http://"
      "http://"+self.website_url
    else 
      return self.website_url
    end
  end
  
  def self.highest_role
    return Setting.find_by_name("roles").actual_value[-2]
  end
  
  def self.roles
    return Setting.find_by_name("roles").actual_value
  end
end

rails/app/controllers/researchers_controller.rb
class ResearchersController < ApplicationController
  before_filter :login_required, except: [:index, :show]
  before_filter :admin_required, only: [:destroy, :panel]

  def index
    @page_title = "Researchers"
    #removed dope-ass join because paginate wouldn't play nice.
    if current_user && current_user.admin?
    @researchers = Researcher.paginate(:page => params[:page], :per_page => 16, :order => "id desc")
    else
      @researchers = Researcher.where(:hidden_account => false).paginate(:page => params[:page], :per_page => 16, :order => "id desc")
    end
  end

  def dashboard
    @page_title = "Dashboard"
    @researcher = Researcher.find(current_user.id)
    @curations = @researcher.curations.where("status != 'hidden'").paginate(:page => params[:page], :per_page => 10, :order => "id desc")
    # @curations = @researcher.curations.order(:created_at)
  end

  def show
    @researcher = Researcher.where(user_name: params[:user_name]).first
    @page_title = @researcher.name
    @curations = @researcher.curations.where("status != 'hidden'").paginate(:page => params[:page], :per_page => 20, :order => "id desc", :limit => 10)
  end

  def edit
    @researcher = Researcher.find_by_user_name(params[:user_name])
    @page_title = "Editing "+@researcher.name
  end

  def new
    # NOTE: Not your typical 'new' because the user is already created
    @researcher = Researcher.find_by_user_name(params[:user_name])
  end

  def update
    @researcher = Researcher.find_by_user_name(params[:user_name], select: [:id, :user_name])
    respond_to do |format|
      if @researcher.update_attributes(params[:researcher])
        format.html { redirect_to @researcher, flash: { success: "Your info has been updated." } }
        format.js
      else
        format.html { render action: 'edit', flash: { error: @reseacher.errors } }
        format.js
      end
    end
  end

  def destroy
    @researcher = Researcher.find_by_user_name(params[:user_name], select: [:id])
    respond_to do |format|
      if @researcher.destroy
        format.html { redirect_to @researcher, notice: "Researcher successfully updated." }
        format.js
      else
        format.html { render action: 'edit' }
        format.js
      end
    end
  end
  
  def panel
  end
  
  def upgrade
    @researcher = Researcher.find_by_user_name(params[:user_name])
    roles = Setting.find_by_name("roles").actual_value
    @researcher.role = roles[roles.index(@researcher.role)+1]
    @researcher.upgrade_requested = false
    @researcher.save!
    redirect_to request.referer
  end

  def request_upgrade
    @researcher = Researcher.find_by_user_name(params[:user_name])
    @researcher.upgrade_requested = true
    @researcher.save!
    redirect_to request.referer
  end
end

rails/app/helpers/researchers_helper.rb
module ResearchersHelper
  def link_to_twitter(researcher, opts={})
    opts[:target] ||= '_blank'
    link_to "@#{researcher.user_name}", researcher.twitter_url, opts
  end
end

rails/app/views/researchers/_form.html.slim
= form_for(@researcher, class: 'form-horizontal') do |f|
  = f.hidden_field :first_time, value: false
  fieldset
    .control-group
      .span5
        .controls
          = f.label :name, 'Name *', class: 'control-label'
          = f.text_field :name, class: 'input-xlarge required', required: 'required'
        .controls
          = f.label :email, "E-mail Address *", class: 'control-label'
          = f.text_field :email, class: 'input-xlarge required email', required: 'required'
        .controls
          = f.label :info, 'Bio', class: 'control-label'
          = f.text_area :info, class: 'input-xlarge'
      .span5
        .controls
          = f.label :website_url, "Personal Website", class: 'control-label'
          = f.text_field :website_url, class: 'input-xlarge url'
        .controls
          = f.label :affiliation, class: 'control-label'
          = f.text_field :affiliation, class: 'input-xlarge'
        .controls
          = f.label :affiliation_url, "Affiliate URL", class: 'control-label'
          = f.text_field :affiliation_url, class: 'input-xlarge url'
        .controls
          = f.label :time_zone, class: 'control-label'
          = f.time_zone_select :time_zone, ActiveSupport::TimeZone.all, default: 'UTC', class: 'input-xlarge'
        .controls
          = f.label :location, class: 'control-label'
          = f.text_field :location, class: 'input-xlarge'
        .controls
          = f.check_box :share_email, class: 'input-xlarge pull-left'
          = f.label :share_email, "Turn on notifications?", class: 'control-label'
        .controls
          = f.check_box :private_data, class: 'input-xlarge pull-left'
          = f.label :private_data, " Make my datasets private?", class: 'control-label'
        .controls
          = f.check_box :hidden_account, class: 'input-xlarge pull-left'
          = f.label :hidden_account, " Make my account private?", class: 'control-label'
        .form-actions
          = f.submit 'Update', class: 'btn btn-primary'

rails/app/views/researchers/dashboard.html.slim
.row
  .span12
    h2 My Datasets
    hr
    == render partial: '/curations/table', locals: {curations: @curations}
.row
  .span12
    p.align-center
      = link_to new_dataset_path, class: 'btn btn-large btn-primary' do
        i.icon-plus.icon-white
        |  New Dataset
  // .span5
    p.align-center
      = link_to "Add a Dataset", new_dataset_path, class: 'btn btn-large btn-primary'
- hidden_curations = Curation.where(:researcher_id => @researcher.id, :status => "hidden").count
- if hidden_curations!=0 && @researcher.id == current_user.id
  p You currently have #{hidden_curations} hidden #{hidden_curations == 1 ? "dataset" : "datasets"}, as you, and no other users, have not looked at the dataset in a month. 
  = link_to "Would you like two review these?", search_datasets_path(:hidden => true, :researcher_id => @researcher.id)

rails/app/views/researchers/edit.html.slim
.row
  .span12
    h2 Editing #{@researcher.name}
  .span12
    == render 'form'

rails/app/views/researchers/index.html.slim
/* .row*/
  .span6.offset3
    h2 Researchers
    p
      table.table
        /* .table-striped*/
        /* .table-bordered*/
        thead
          tr
            /* th #*/
            th Name
            th Twitter
            th Datasets
        tbody
          - @researchers.each_with_index do |researcher, i|
            tr
              /* td = i+1*/
              td = link_to researcher.name, researcher
              /* td = link_to researcher.user_name, researcher.twitter_url*/
              td = link_to_twitter researcher
              td = researcher.curations_count

- @researchers.each_slice(4) do |slice|
  .row
    - for researcher in slice
      .span3.researcher
        - if current_user && current_user.admin? && researcher.upgrade_requested
          .well.upgrade_requested
            - if researcher.user_name == "saumar"
              img.pull-left.twitter-pic src=Researcher.first(:conditions => {:user_name => "yleoyleo"}).twitter_pic(:normal)
            - else
              img.pull-left.twitter-pic src=researcher.twitter_pic(:normal)
            h4 = link_to researcher.name, researcher
            p = link_to_twitter researcher
            p
              strong #{researcher.curations_count}
              |  Dataset#{'s' if researcher.curations_count != 1}
        - else
          .well
            - if researcher.user_name == "saumar"
              img.pull-left.twitter-pic src=Researcher.first(:conditions => {:user_name => "yleoyleo"}).twitter_pic(:normal)
            - else
              img.pull-left.twitter-pic src=researcher.twitter_pic(:normal)
            h4 = link_to researcher.name, researcher
            p = link_to_twitter researcher
            p
              strong #{researcher.curations_count}
              |  Dataset#{'s' if researcher.curations_count != 1}


= will_paginate(@researchers)

rails/app/views/researchers/new.html.slim
.row
  .span12
    .page-header
      h1 Welcome to 140kit!
    h3 Tell us a bit about yourself...
  .span12
    == render 'form'

rails/app/views/researchers/show.html.slim
.row
  .span4
    .well
      .page-header
        img.pull-left.twitter-pic src=@researcher.twitter_pic(:bigger)
        h1 = @researcher.name
        h3 = link_to_twitter(@researcher)
      = p @researcher.info if @researcher.info
      ul
        - if @researcher.website_url && !@researcher.website_url.empty?
          li 
            a href=@researcher.safe_website_url Website
        - if @researcher.affiliation
          li
            - if @researcher.affiliation_url && !@researcher.affiliation_url.empty?
              | Affiliation: 
              a href=@researcher.affiliation_url = @researcher.affiliation
            - else
              | Affiliation: 
              = @researcher.affiliation
        - if @researcher == current_user
          li
            | Access Level: 
            = @researcher.role+" "
            - if !@researcher.upgrade_requested && @researcher.role != Researcher.highest_role
              span (
              = link_to "Request Upgrade", request_upgrade_researcher_path(@researcher)
              span )
        - if @researcher.location
          li 
            | Hailing from: 
            = @researcher.location
        - if @researcher.join_date
          li 
            | Member since: 
            = @researcher.human_join_date
      - if @researcher == current_user
        a href=edit_researcher_path(@researcher) Edit
      - if current_user && current_user.admin? && @researcher.upgrade_requested
        = link_to "Upgrade Account", upgrade_researcher_path(@researcher)
  .span8
    h3 Most Recent Datasets
    == render partial: 'curations/table'
  /* .span4*/
    == render partial: 'curations/table'
  