rails/config/routes.rb
WWW140kit::Application.routes.draw do

  resources :auth_users

  resources :analytical_offerings, path: '/analytics', only: [:index, :edit, :new, :create] do
    member do
      put 'details' => :update, as: :update
      get 'details' => :show, as: ''
      get ':curation_id/add' => :add, as: :add
      post ':curation_id/validate' => :validate, as: :validate
      get ':curation_id/verify' => :verify, as: :verify
    end
  end

  scope '/analytics/:id' do
    get '' => 'analysis_metadata#show', as: :analysis_metadata
    get ':graph_id/graph' => 'analysis_metadata#graph', as: :analysis_metadata_graph
    delete '' => 'analysis_metadata#destroy'
  end

  resources :instances, only: [] do
    member do
      get 'kill' => :kill_instance
      get ':id' => :show_instance, as: ''
    end
    get '' => :index_instance, as: '', on: :collection
  end

  resources :instances, as: :machines, path: '/machines', only: [] do
    get '' => :index_machine, as: '', on: :collection
    member do
      get 'edit' => :edit
      get 'kill' => :kill_machine
      get '' => :show_machine, as: ''
      post 'update' => :update
    end
  end

  get '/datasets/new/location' => 'curations#new_location', as: :new_location_dataset
  get '/datasets/new/term' => 'curations#new_term', as: :new_term_dataset
  get '/datasets/new/user' => 'curations#new_user', as: :new_user_dataset
  get '/datasets/validate/users' => 'curations#validate_users', as: :validate_user_dataset
  get '/datasets/:id/alter/:stream_type' => 'curations#new', as: :alter_dataset
  get '/tags/drop_relation' => 'tags#drop_relation', as: :drop_tag_relation
  resources :curations, only: [:index, :create, :new, :show, :validate, :analyze, :alter, :import, :verify, :destroy], path: '/datasets', as: :datasets do
    member do
      get 'verify'
      get 'analyze'
      get 'import'
      get 'archive'
    end
    get 'search', on: :collection
  end
  post '/datasets/validate' => 'curations#validate', as: :dataset_validate
  get '/:user_name/datasets' => 'curations#researcher', as: :researcher_datasets
  get '/analysis/:curation_id/:analysis_metadata_id' => 'analysis_metadata#results', as: :curation_analysis

  get '/admin/panel' => 'admin#panel', as: :admin_panel

  resources :researchers, only: [:index]
  scope '/researchers/:user_name' do
    get '' => 'researchers#show', as: :researcher
    get 'edit' => 'researchers#edit', as: :edit_researcher
    get 'new' => 'researchers#new', as: :new_researcher
    get 'upgrade' => 'researchers#upgrade', as: :upgrade_researcher
    get 'request_upgrade' => 'researchers#request_upgrade', as: :request_upgrade_researcher
    put '' => 'researchers#update'
    delete '' => 'researchers#destroy'
  end
  get '/datasets/:curation_id/tweets/' => 'tweets#index', as: :tweets
  get '/datasets/:curation_id/users/' => 'users#index', as: :users

  get 'dashboard' => 'researchers#dashboard', as: :dashboard

  resources :posts, except: [:show]
  get '/posts/search' => 'posts#index', as: :search_posts

  get '/posts/:id/:slug' => 'posts#show', as: :post
  get '/about' => 'posts#about', as: :about

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root to: 'home#index'
  resources :analytical_offering_variable_descriptors, path: '/variables'
  get '/dependencies/:id/new' => 'analytical_offering_requirements#new', as: :new_dependency
  resources :analytical_offering_requirements, path: '/dependencies'
  get '/variables/:id/new' => 'analytical_offering_variable_descriptors#new', as: :new_variable
  resources :tags
  resources :settings

end

rails/app/models/curation.rb
class Curation < ActiveRecord::Base
  belongs_to :researcher
  has_and_belongs_to_many :datasets, :join_table => "curation_datasets"
  has_and_belongs_to_many :tags, :join_table => "curation_tags"
  has_many :analysis_metadatas
  has_many :graphs
  
  def tweets_count
    return datasets.collect{|d| d.tweets_count}.sum
  end
  
  def entities_count
    return datasets.collect{|d| d.entities_count}.sum
  end

  def users_count
    return datasets.collect{|d| d.users_count}.sum
  end
  
  def self.max_time
    return 1.week
  end
  
  def self.default_time_series
    return 5.minutes
  end
  
  def self.default_step
    return 10.minutes
  end
  
  def current_status(current_user=nil)
    case self.status
    when "tsv_storing"
      return "Collecting"
    when "tsv_stored"
      return "Finishing collection"
    when "needs_import"
      return "Ready for analysis"
    when "imported"
      return "Live"
    when "needs_drop"
      return "Dropping"
    when "dropped"
      return "Archived"
    when "zero_data"
      return "No Tweets Found!"
    when "hidden"
      return "In Deep Archive"
    else
      return "Unknown"
    end
  end
  
  def current_options(current_user=nil)
    #this is bad design, I know. It's just the first thing I thought of that could do this - problem is I'm not sure you can access a specific object from within model?
    case self.status
    when "tsv_storing"
      if self.tweets_count == 0
        return "No Tweets Yet"
      else
        return "<a href='/datasets/#{self.id}/analyze'>Set Analytics</a>"
      end
    when "tsv_stored"
      if self.tweets_count == 0
        return "No Tweets"
      else
        return "<a href='/datasets/#{self.id}/analyze'>Set Analytics</a> | <a href='/datasets/#{self.id}/import'>Bring it live</a>"
      end
    when "needs_import"
      return "Sit tight..."
    when "imported"
      if self.tweets_count == 0
        return "No Tweets"
      else
        return "<a href='/datasets/#{self.id}/analyze'>Set Analytics</a>"
      end
    when "needs_drop"
      return "Sit tight..."
    when "dropped"
      if self.tweets_count == 0
        return "No Tweets"
      else
        return "<a href='/datasets/#{self.id}/analyze'>Set Analytics</a> | <a href='/datasets/#{self.id}/import'>Restore</a>"
      end
    when "zero_data"
      if self.researcher_id == current_user.id
        return "No Tweets Found!"
      else
        return "No Tweets Found!"
      end
    when "hidden"
      if self.tweets_count == 0
        return "No Tweets"
      else
        return "<a href='/datasets/#{self.id}/import'>Bring it live</a>"
      end
    else
      return "Sit tight..."
    end
  end
  
end

rails/app/helpers/curations_helper.rb
module CurationsHelper
  def exact_time(seconds)
    statement = ""
    time_set = []
    time_set << seconds/1.week
    seconds = seconds-time_set.last.weeks
    time_set << seconds/1.day
    seconds = seconds-time_set.last.days
    time_set << seconds/1.hour
    seconds = seconds-time_set.last.hours
    time_set << seconds/1.minute
    seconds = seconds-time_set.last.minutes
    time_set << seconds
    ordered_set = ["Weeks", "Days", "Hours", "Minutes", "Seconds"]
    i = 0
    time_set.each do |t|
      if t == 1
        statement << "#{t} #{ordered_set[i].chop}, "
      elsif t != 0
        statement << "#{t} #{ordered_set[i]}, "
      end
      i+=1
    end
    return statement.chop.chop
  end
  
  def current_status(curation)
    case curation.status
    when "tsv_storing"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset is currently streaming. Take this opportunity to review available analytics, and add the ones you think may be useful for your research. When the data stream is complete, you will be able to import the dataset, at which point analysis can be run."
        else
          return "This dataset is currently streaming. Take this opportunity to review available analytics, and add the ones you think may be useful for your research. When the data stream is complete, you will be able to import the dataset, at which point analysis can be run."
        end
      else
        return "This dataset is currently streaming."
      end
    when "tsv_stored"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset has now been stored! At this point, you may add any analytical process you want. After you're done, go ahead and import the dataset, and we will begin processing analytics."
        else
          return "This dataset has now been stored! At this point, you may add any analytical process you want. After you're done, go ahead and import the dataset, and we will begin processing analytics."
        end
      else
        return "This dataset has now been stored! At this point, you can add any analytical process you want if you log in."
      end
    when "needs_import"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset has been queued for import. Please come back when the data import is complete."
        else
          return "This dataset has been queued for import. Please come back when the data import is complete."
        end
      else
        return "This dataset has been queued for import. Please come back when the data import is complete."
      end
    when "imported"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset is live! You can add, edit, and alter any and all analytics you want, and we'll keep this dataset online so long as people actively use it (If this dataset goes one week without any activity, including someone looking at it, we will archive it automatically)."
        else
          return "This dataset is live! We'll keep this dataset online so long as people actively use it."
        end
      else
        return ""
      end
    when "needs_drop"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset is in the process of being archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
        else
          return "This dataset is in the process of being archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
        end
      else
        return "This dataset is in the process of being archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
      end      
    when "dropped"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset has been archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
        else
          return "This dataset has been archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
        end
      else
        return "This dataset has been archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
      end   
    when "hidden"
      if current_user
        if current_user.id == curation.researcher_id
          return "Your dataset has been deep archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
        else
          return "This dataset has been deep archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
        end
      else
        return "This dataset has been deep archived. At this point, you can't take any actions. To re-import the dataset and bring it live again, just select that option."
      end   
    when "zero_data"
      if current_user
        if current_user.id == curation.researcher_id
          return "Unfortunately, no tweets were found for the time period you selected."
        else
          return "Unfortunately, no tweets were found for the time period the researcher selected."
        end
      else
        return "Unfortunately, no tweets were found for the time period the researcher selected."
      end
    end
  end
  
  def next_step_badge_text(curation)
    case curation.status 
    when "tsv_storing"
      return "Select Analytics"
    when "tsv_stored"
      return "Bring it live"
    when "needs_import"
      return "Select Analytics"
    when "imported"
      return "Have Fun!"
    when "needs_drop"
      return "Hold on"
    when "dropped"
      return "Bring it live"
    when "zero_data"
      return "Remove"
    when "hidden"
      return "Bring it live"
    end
  end

  def next_step_badge(curation)
    case curation.status
    when "tsv_storing"
      return link_to next_step_badge_text(curation), analyze_dataset_url(curation), {:class => "btn btn-primary btn-large"}
    when "tsv_stored"
      return link_to next_step_badge_text(curation), import_dataset_url(curation), {:class => "btn btn-primary btn-large"}
    when "needs_import"
      return link_to next_step_badge_text(curation), analyze_dataset_url(curation), {:class => "btn btn-primary btn-large"}
    when "imported"
      return link_to next_step_badge_text(curation), "#", {:class => "btn btn-primary btn-large"}
    when "needs_drop"
      return link_to next_step_badge_text(curation), "#", {:class => "btn btn-primary btn-large"}
    when "dropped"
      return link_to next_step_badge_text(curation), import_dataset_url(curation), {:class => "btn btn-primary btn-large"}
    when "zero_data"
      return link_to next_step_badge_text(curation), dataset_path(curation), {:method => :delete, :class => "btn btn-primary btn-large"}
    when "hidden"
      return link_to next_step_badge_text(curation), import_dataset_url(curation), {:class => "btn btn-primary btn-large"}
    end
  end
end

rails/app/views/curations/_analytics.html.slim
- analysis_metadatas ||= @analysis_metadatas
table.table.table-striped.table-bordered
  thead
    tr
      th Type
      th Status
      th Options
  tbody
    - for analysis_metadata in analysis_metadatas
      tr
        td
          | 
          a href=analytical_offering_path(analysis_metadata.analytical_offering.id) #{analysis_metadata.analytical_offering.title}
        td = analysis_metadata.status
        td = analysis_metadata.links.join(" | ").html_safe

= will_paginate(analysis_metadatas, :param_name => :analysis_page)

rails/app/views/curations/_analyze.html.slim
h1 Analysis for #{link_to @curation.name, dataset_path(@curation)}
- if @curation.tweets_count >= 1
  h2 Already Applied
  - if @analysis_metadatas.length == 0
    p No analytical offerings currently applied!
  - else
    == render partial: '/analysis_metadata/table', :locals => {:analysis_metadatas => @analysis_metadatas}

  h2 Available
  - if @analytical_offerings.length == 0
    p No more analytical offerings currently available!
  - else
    == render partial: '/analytical_offerings/table', :locals => {:analytical_offerings => @analytical_offerings}

- else
  p You can't add any analytics until we have received at least one tweet.

rails/app/views/curations/_form.html.slim
- @researcher = Researcher.find(current_user.id)
.row
  .span12
    = form_tag(datasets_path, id: 'new-curation-form') do
      fieldset

        .control-group
          == render "curations/#{stream_type}_field"
          .controls
            label.control-label Enter a name for this dataset (optional, default will be the terms you selected)
            = text_field_tag :name, params[:name], :class => "input-xlarge"
          .controls
            label.control-label Is this Dataset Private?
            = check_box_tag :privatized, true, false, :class => "input-xlarge"
          .controls
            label.control-label How long should we collect this data?
            //= range_field_tag :end_time, params[:end_time]||Curation.default_time_series, :in => Curation.default_time_series..Curation.max_time, :step => Curation.default_step, :class => 'input-full'
            = hidden_field_tag :end_time, params[:end_time] || Curation.default_time_series
            = hidden_field_tag :stream_type, stream_type
            #time-slider
          p
            h3.align-center#time_output #{exact_time(Curation.default_time_series)}
          .form-actions.align-center
            p
              a.btn.btn-primary.btn-large#review-curation-params Submit
            p = link_to 'Back', '#', id: 'back-to-new-curation', class: 'btn'

rails/app/views/curations/_location.html.erb
<script type="text/javascript">
var shiftClicked = false;
var map;
var dragging = false;
var rect;
var pos1, pos2;
$(document).ready(function() {
    initMap();
});
function initMap() {
    var latlng = new google.maps.LatLng(0,0);
    var settings = {
        zoom: 2,
        center: latlng,
        mapTypeControl: true,
        navigationControl: true,
        streetViewControl: false,
        mapTypeControl: false,
        scaleControl: false,
        overviewMapControl: false,
        disableDefaultUI: true,
        navigationControlOptions: {
            style: google.maps.NavigationControlStyle.SMALL
        },
        mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var mapElem = $("#map-canvas");
    map = new google.maps.Map(mapElem[0], settings);
    rect = new google.maps.Rectangle({
                map: map,
                fillColor: '#496BBE',
                strokeColor: "#496BBE",
                strokeOpacity: 1.0,
                strokeWeight: 2,
                editable: true
            });
    google.maps.event.addListener(rect, 'bounds_changed', function(mEvent) {
      updateLocationVal();
    })
    google.maps.event.addListener(map, 'mousedown', function(mEvent) {
        e = window.event;
         if (e.shiftKey) {
           map.draggable = false;
           latlng1 = mEvent.latLng;
           dragging = true;
           pos1 = mEvent.pixel;           
         };
    });

    google.maps.event.addListener(map, 'mousemove', function(mEvent) {
        map.draggable = true;
        latlng2 = mEvent.latLng;
        console.log(mEvent);
        showRect();
    });

    google.maps.event.addListener(map, 'mouseup', function(mEvent) {
        map.draggable = true;
        dragging = false;

    });
    
    google.maps.event.addListener(rect, 'mouseup', function(data){
        map.draggable = true;
        dragging = false;
    });
    

}
function updateLocationVal(){
  var minLat = roundTo(rect.getBounds().getSouthWest().lat(), 3);
  var maxLat = roundTo(rect.getBounds().getNorthEast().lat(), 3);
  var minLng = roundTo(rect.getBounds().getSouthWest().lng(), 3);
  var maxLng = roundTo(rect.getBounds().getNorthEast().lng(), 3);
  $('#latlon').val(minLng+","+maxLat+","+maxLng+","+minLat);
}
function roundTo(val, place){
  return Math.round(val*Math.pow(10,place))/Math.pow(10,place);
}
function showRect() {
  if (dragging){
    if (rect === undefined) {
      rect = new google.maps.Rectangle({
        map: map,
        fillColor: '#496BBE',
        strokeColor: "#FF0000",
        strokeOpacity: 1.0,
        strokeWeight: 2,
        editable: true
      });
    };
    var latLngBounds = new google.maps.LatLngBounds(latlng1, latlng2);
    rect.setBounds(latLngBounds);
      updateLocationVal();
  };
}

</script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<div id="info">Below is a map - pan around to the area of interest, and then, while holding SHIFT, click on the map to begin drawing a rectangle to collect data from. Twitter's API only allows for rectangular boxes, or "bounding boxes", as valid input for data. As such, come up with an approximate "bounding box", and edit as necessary. When you are satisfied, click 'validate' to continue.</div><br/>
<div class="span12" id="map-wrap">
    <div id="map-canvas"></div>
    <%= form_tag(dataset_validate_path, :method => "post") do %>
      <%= hidden_field_tag :stream_type, params[:stream_type] %>
      <br/>
      <br/>
      <br/>
      <label class="control-label">Enter a name for this dataset (optional, default will be the terms you selected):</label>
      <%= text_field_tag :name, params[:name], :class => "input-xlarge comma-separated-input" %>
      <label class="control-label">Twitter's API input for the Bounding box drawn:</label>
      <%= text_field_tag :params, params[:params], :class => "input-xlarge comma-separated-input", :id => "latlon" %>
      <label class="control-label">How long should we collect this data?</label>
      <%= hidden_field_tag :end_time, params[:end_time]||Curation.default_time_series %>
      <div id="time-slider"></div>
      <br/>
      <h3 class="align-center" id="time_output"><%= exact_time(Curation.default_time_series) %></h3>
      <br/>
      <br/>
      <br/>
    <%= submit_tag 'Validate', class: 'btn btn-primary' %>
    <% end %>
</div>

rails/app/views/curations/_location_field.html.slim
p.controls
  | Below is a map - pan around to the area of interest, and then, 
  | while holding SHIFT, click on the map to begin drawing a rectangle 
  | to collect data from. Twitter's API only allows for rectangular 
  | boxes, or "bounding boxes", as valid input for data. As such, come 
  | up with an approximate "bounding box", and edit as necessary. When 
  | you are satisfied, click 'validate' to continue.

#map-canvas
.controls
  label.control-label Twitter's API input for the Bounding box drawn:
  = text_field_tag :params, params[:params], :class => "input-xlarge required", :id => "latlon", :required => true

rails/app/views/curations/_table.html.slim
- curations ||= @curations
- show_options ||= true
- if curations.empty?
  p
    h3.gray9.align-center No datasets.
- else
  table.table.table-striped.table-bordered
    thead
      tr
        th Name
        th Age
        th Status
        th Tweets
        th Users
    tbody
      - for curation in curations
        tr
          td = link_to curation.name, dataset_path(curation)
          td = time_ago_in_words(curation.created_at)
          td = curation.current_status
          td = number_with_delimiter(curation.tweets_count)
          td = number_with_delimiter(curation.users_count)

  = will_paginate(curations)

rails/app/views/curations/alter.html.slim
h1 = "Alter #{params[:stream_type].capitalize} Curation"
- if params[:stream_type] == "term"
  == render partial: 'form'
- elsif params[:stream_type] == "location"
  == render partial: 'location'

rails/app/views/curations/analyze.html.slim
h1 Analysis for #{link_to @curation.name, dataset_path(@curation)}
- if @curation.tweets_count >= 1
  h2 Already Applied
  - if @analysis_metadatas.length == 0
    p No analytical offerings currently applied!
  - else
    == render partial: '/analysis_metadata/table', :locals => {:analysis_metadatas => @analysis_metadatas}

  h2 Available
  - if @analytical_offerings.length == 0
    p No more analytical offerings currently available!
  - else
    == render partial: '/analytical_offerings/table', :locals => {:analytical_offerings => @analytical_offerings}

- else
  p You can't add any analytics until we have received at least one tweet.

rails/app/views/curations/index.html.slim
.row
  .span10.offset1
    .page-header
      h1 Datasets
.row
  .span12
    == render partial: 'table', locals: {curations: @curations}
- if current_user
  p.align-center
    = link_to new_dataset_path, class: 'btn btn-large btn-primary' do
      i.icon-plus.icon-white
      |  New Dataset

rails/app/views/curations/new.html.slim
.row
  .span12
    .page-header
      h1 New Dataset

#curation-form.hide
#term-or-location-or-user
  .row
    .span4
      .well
        h2 Track terms
        p Collect all tweets that contain a given word or words.
        p.align-center
          = link_to 'Select', new_term_dataset_path, class: 'btn btn-large btn-primary', remote: true
    .span4
      .well
        h2 Track location
        p Collect all geotagged tweets originating from a location.
        p.align-center
          = link_to 'Select', new_location_dataset_path, class: 'btn btn-large btn-primary', remote: true
    .span4
      .well
        h2 Track Users
        p Collect all tweets posted by a set of given users
        p.align-center
          = link_to 'Select', new_user_dataset_path, class: 'btn btn-large btn-primary', remote: true

rails/app/views/curations/new_location.js.erb
$('#term-or-location-or-user').slideUp();
$('#curation-form').html("<%=j render 'curations/form', stream_type: 'location' %>").slideDown();
$('#time-slider').slider({
    min: 60,
    max: 604800,
    slide: function(event, ui) {
        $('#time_output').html(exact_time(ui.value));
        $('#end_time').val(ui.value);
      }
});
initMap('#map-canvas');
$('#new-curation-form').validate();

rails/app/views/curations/new_term.js.erb
$('#terms-or-location').slideUp();
$('#curation-form').html("<%=j render 'curations/form', stream_type: 'terms' %>").slideDown();
$('#time-slider').slider({
    min: 60,
    max: 604800,
    slide: function(event, ui) {
        $('#time_output').html(exact_time(ui.value));
        $('#end_time').val(ui.value);
      }
});
$('#new-curation-form').validate();

rails/app/views/curations/new_user.js.erb
$('#term-or-location-or-user').slideUp();
$('#curation-form').html("<%=j render 'curations/form', stream_type: 'users' %>").slideDown();
$('#time-slider').slider({
    min: 60,
    max: 604800,
    slide: function(event, ui) {
        $('#time_output').html(exact_time(ui.value));
        $('#end_time').val(ui.value);
      }
});
$('#new-curation-form').validate();

rails/app/views/curations/researcher.html.slim
.row
  .span10.offset1
    == render partial: 'table', curations: @curations, show_options: true